# Generated by Django 5.0.6 on 2024-06-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
