# Generated by Django 5.0.6 on 2024-06-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_remove_group_name_group_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='sender.contact'),
        ),
    ]
