# Generated by Django 5.0.6 on 2024-06-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_alter_contact_name_alter_group_group_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='sender.contact'),
        ),
    ]
