# Generated by Django 5.0.6 on 2024-06-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_rename_group_name_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='sender.contact'),
        ),
    ]
